name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "tauri-app/src/**"
      - "tauri-app/src-tauri/**"
      - "tauri-app/package.json"
  pull_request:
    branches:
      - main
    paths:
      - "tauri-app/src/**"
      - "tauri-app/src-tauri/**"
      - "tauri-app/package.json"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build Linux x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            libglib2.0-dev \
            libgtk-3-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: tauri-app

      - name: Check Tauri version
        run: bun tauri --version
        working-directory: tauri-app

      - name: Set environment variables
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          echo "TAURI_SIGNING_PRIVATE_KEY=${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "TAURI_SIGNING_PRIVATE_KEY_PASSWORD=${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Tauri App
        run: bun tauri build --target x86_64-unknown-linux-gnu
        working-directory: tauri-app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-linux-x64-ci
          path: |
            tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.deb
            tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.rpm
            tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.AppImage