name: Publish Cross-Platform

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
  VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
  TAURI_BUNDLE: all
  
jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: Linux x86_64
            artifact-name: MCPLinker-linux-x64
            artifact-path: |
              tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.deb
              tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.rpm
              tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.AppImage
              tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.deb.sig
              tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.rpm.sig
              tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.AppImage.sig
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: Windows x86_64
            artifact-name: MCPLinker_Windows_x64
            artifact-path: |
              tauri-app/src-tauri/target/release/bundle/**/*.exe
              tauri-app/src-tauri/target/release/bundle/**/*.msi
              tauri-app/src-tauri/target/release/bundle/**/*.exe.sig
              tauri-app/src-tauri/target/release/bundle/**/*.msi.sig

    runs-on: ${{ matrix.platform.os }}
    name: Build ${{ matrix.platform.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: tauri-app

      - name: Build Tauri App
        run: bun tauri build ${{ runner.os == 'Linux' && format('--target {0}', matrix.platform.target) || '' }}
        working-directory: tauri-app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact-name }}
          path: ${{ matrix.platform.artifact-path }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ${{ matrix.platform.artifact-path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}