name: Build Tauri App for Windows

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - ".github/workflows/tauri-ci-win.yml"
      - "tauri-app/src/**"
      - "tauri-app/src-tauri/**"
      - "tauri-app/package.json"
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # set BUILD_KEY auto run
      - name: Set build type
        id: build-type
        run: |
          if (Test-Path env:BUILD_KEY) {
            echo "Using signing key"
            echo "HAS_KEY=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "Building without signing key"
            echo "HAS_KEY=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
        env:
          BUILD_KEY: ${{ secrets.BUILD_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun on Windows
        shell: pwsh
        run: |
          irm https://bun.sh/install.ps1 | iex
          echo "$HOME\.bun\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Install dependencies bun and Check Tauri version
        run: |
          bun install
          bun tauri --version
        working-directory: tauri-app

      - name: Set environment variables
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> $env:GITHUB_ENV
          echo "VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }}" >> $env:GITHUB_ENV
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $env:GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Rust app with bun
        run: bun tauri build
        working-directory: tauri-app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MCP-Linker-Windows-CI
          path: |
            tauri-app/src-tauri/target/release/bundle/**/*.exe
            tauri-app/src-tauri/target/release/bundle/**/*.msi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            tauri-app/src-tauri/target/release/bundle/**/*.exe
            tauri-app/src-tauri/target/release/bundle/**/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
